import { Router, Response } from 'express';
import { PrismaClient } from '@prisma/client';
import { authMiddleware, AuthRequest } from '../middlewares/auth.middleware';
import { adminMiddleware } from '../middlewares/admin.middleware';
import { superadminMiddleware } from '../middlewares/superadmin.middleware';
import bcrypt from 'bcryptjs';
import crypto from 'crypto';
import {
  getActivePartnerShareTotal,
  markWithdrawalPaid,
  autoOffboardIfFullyPaid,
  rejectWithdrawal,
  sendPartnerWelcome,
} from '../services/partner.service';
import { pageArgs, paginated } from '../lib/pagination';

const router = Router();
const prisma = (((globalThis as any).__czPrisma ??= new PrismaClient()) as PrismaClient);

// Mounted at /api/admin. Reads need admin; writes that change revenue
// attribution (create/edit/remove partners) need superadmin — same policy
// as coproducers.
router.use(authMiddleware);
router.use(adminMiddleware);

const round2 = (v: number) => Math.round(v * 100) / 100;

// ── GET /api/admin/partners — list partners + rollups + share total ───────
router.get('/partners', async (req: AuthRequest, res: Response) => {
  try {
    const { page, pageSize, skip, take } = pageArgs(req);
    const [accounts, total] = await Promise.all([
      prisma.partnerAccount.findMany({
        orderBy: { createdAt: 'asc' },
        skip,
        take,
        include: { user: { select: { id: true, name: true, email: true, phone: true } } },
      }),
      prisma.partnerAccount.count(),
    ]);

    // Roll up commissions per partner (lifetime earnings) and the available
    // balance separately, in two grouped queries. Per-partner, so grouping over
    // just this page's ids preserves each visible row's rollups.
    const ids = accounts.map((a) => a.id);
    const [lifetime, byStatus] = await Promise.all([
      prisma.partnerCommission.groupBy({
        by: ['partnerId'],
        where: { partnerId: { in: ids }, status: { not: 'refunded' } },
        _sum: { amount: true },
        _count: { _all: true },
      }),
      prisma.partnerCommission.groupBy({
        by: ['partnerId', 'status'],
        where: { partnerId: { in: ids } },
        _sum: { amount: true },
      }),
    ]);
    const lifeById = new Map(lifetime.map((r) => [r.partnerId, r]));
    const availById = new Map<string, number>();
    for (const r of byStatus) {
      if (r.status === 'available') availById.set(r.partnerId, r._sum.amount ?? 0);
    }

    const items = accounts.map((acc) => ({
      id: acc.id,
      displayName: acc.displayName || acc.user.name,
      roleLabel: acc.roleLabel,
      sharePct: acc.sharePct,
      enabled: acc.enabled,
      payoutMethod: acc.payoutMethod,
      payoutTarget: acc.payoutTarget,
      createdAt: acc.createdAt,
      user: acc.user,
      lifetimeEarnings: round2(lifeById.get(acc.id)?._sum.amount ?? 0),
      lifetimeSales: lifeById.get(acc.id)?._count._all ?? 0,
      availableBalance: round2(availById.get(acc.id) ?? 0),
    }));

    const shareTotal = await getActivePartnerShareTotal();
    // `partners` kept as an alias of `items` for backward compat with the old front.
    // shareTotal stays a global aggregate (not paginated).
    res.json({ ...paginated(items, total, page, pageSize), partners: items, shareTotal });
  } catch (error) {
    console.error('[ADMIN/PARTNERS] List error:', error);
    res.status(500).json({ error: 'Erro ao listar sócios' });
  }
});

// Normalize a Moçambique phone to digits with country code (mirrors the
// webhook/coproducer normalization).
function normalizePhone(raw: string): string {
  let clean = String(raw).replace(/\D/g, '');
  if (clean.length === 9 && clean.startsWith('8')) clean = `258${clean}`;
  return clean;
}

// ── POST /api/admin/partners — create/assign a partner (superadmin) ───────
// Body: { userEmail, phone?, name?, sharePct, roleLabel?, displayName? }
//
// If a user with `userEmail` already exists, it is promoted to partner (and
// its phone is updated when provided). Otherwise a new staff user is created
// from name + email + phone. Either way, login credentials are sent to the
// partner's WhatsApp (fresh password generated by sendPartnerWelcome).
router.post('/partners', superadminMiddleware, async (req: AuthRequest, res: Response) => {
  try {
    const { userEmail, phone, name, sharePct, roleLabel, displayName } = req.body || {};
    if (!userEmail || sharePct == null) {
      return res.status(400).json({ error: 'userEmail e sharePct são obrigatórios' });
    }
    if (sharePct < 0 || sharePct > 100) {
      return res.status(400).json({ error: 'sharePct deve estar entre 0 e 100' });
    }

    const email = String(userEmail).toLowerCase().trim();
    const cleanPhone = phone ? normalizePhone(phone) : '';

    let user = await prisma.user.findUnique({ where: { email } });

    if (!user) {
      // Creating a brand-new staff account requires a phone (to deliver the
      // credentials) — the User.phone column is also @unique/NOT NULL.
      if (!cleanPhone) {
        return res.status(400).json({
          error: 'Usuário não existe. Informe o WhatsApp (phone) para criar a conta e enviar o acesso.',
        });
      }
      const phoneTaken = await prisma.user.findUnique({ where: { phone: cleanPhone } });
      if (phoneTaken) {
        return res.status(400).json({ error: 'Já existe um usuário com esse WhatsApp' });
      }
      // Temporary password — sendPartnerWelcome resets it and delivers the
      // real one. grantedManually keeps this staff account out of MRR counts.
      const tempHash = await bcrypt.hash(crypto.randomUUID(), 10);
      user = await prisma.user.create({
        data: {
          name: (name?.trim() || displayName?.trim() || 'Sócio'),
          email,
          phone: cleanPhone,
          passwordHash: tempHash,
          role: 'member',
          isActive: true,
          subscriptionStatus: 'active',
          grantedManually: true,
        },
      });
    } else {
      const existing = await prisma.partnerAccount.findUnique({ where: { userId: user.id } });
      if (existing) return res.status(400).json({ error: 'Este usuário já é sócio' });
      // Update the phone if a new one was provided and it's free.
      if (cleanPhone && cleanPhone !== user.phone) {
        const phoneTaken = await prisma.user.findFirst({
          where: { phone: cleanPhone, id: { not: user.id } },
        });
        if (!phoneTaken) {
          user = await prisma.user.update({ where: { id: user.id }, data: { phone: cleanPhone } });
        }
      }
    }

    const account = await prisma.partnerAccount.create({
      data: {
        userId: user.id,
        sharePct: Number(sharePct),
        roleLabel: roleLabel?.trim() || null,
        displayName: displayName?.trim() || null,
      },
    });

    // Deliver credentials via WhatsApp. Non-fatal: the partner exists either
    // way; the admin sees whether delivery worked and can resend.
    const welcome = await sendPartnerWelcome({ partnerAccountId: account.id });

    res.json({
      partner: account,
      welcome: { delivered: welcome.delivered, status: welcome.status },
    });
  } catch (error) {
    console.error('[ADMIN/PARTNERS] Create error:', error);
    res.status(500).json({ error: 'Erro ao criar sócio' });
  }
});

// ── POST /api/admin/partners/:id/resend-welcome (superadmin) ──────────────
// Generates a fresh password and re-sends credentials via WhatsApp.
router.post('/partners/:id/resend-welcome', superadminMiddleware, async (req: AuthRequest, res: Response) => {
  try {
    const acc = await prisma.partnerAccount.findUnique({ where: { id: req.params.id } });
    if (!acc) return res.status(404).json({ error: 'Sócio não encontrado' });
    const result = await sendPartnerWelcome({ partnerAccountId: acc.id });
    if (!result.delivered) {
      return res.status(502).json({
        success: false,
        error: `WhatsApp não entregou (status=${result.status}). Senha foi resetada — copie do log do servidor ou tente novamente.`,
      });
    }
    res.json({ success: true, status: result.status });
  } catch (error) {
    console.error('[ADMIN/PARTNERS] resend-welcome error:', error);
    res.status(500).json({ error: 'Erro ao reenviar acesso' });
  }
});

// ── PATCH /api/admin/partners/:id — update (superadmin) ───────────────────
router.patch('/partners/:id', superadminMiddleware, async (req: AuthRequest, res: Response) => {
  try {
    const { sharePct, roleLabel, displayName, enabled } = req.body || {};
    const existing = await prisma.partnerAccount.findUnique({ where: { id: req.params.id } });
    if (!existing) return res.status(404).json({ error: 'Sócio não encontrado' });

    if (sharePct != null && (sharePct < 0 || sharePct > 100)) {
      return res.status(400).json({ error: 'sharePct deve estar entre 0 e 100' });
    }

    const updated = await prisma.partnerAccount.update({
      where: { id: req.params.id },
      data: {
        ...(sharePct != null ? { sharePct: Number(sharePct) } : {}),
        ...(roleLabel != null ? { roleLabel: String(roleLabel).trim() || null } : {}),
        ...(displayName != null ? { displayName: String(displayName).trim() || null } : {}),
        ...(enabled != null ? { enabled: !!enabled } : {}),
      },
    });
    res.json({ partner: updated });
  } catch (error) {
    console.error('[ADMIN/PARTNERS] Update error:', error);
    res.status(500).json({ error: 'Erro ao atualizar sócio' });
  }
});

// ── DELETE /api/admin/partners/:id — remove (superadmin) ──────────────────
// Preserves historical commissions/withdrawals via ON DELETE CASCADE? No —
// cascade would wipe them. We block deletion when history exists and suggest
// disabling instead, keeping the financial trail intact.
router.delete('/partners/:id', superadminMiddleware, async (req: AuthRequest, res: Response) => {
  try {
    const acc = await prisma.partnerAccount.findUnique({ where: { id: req.params.id } });
    if (!acc) return res.status(404).json({ error: 'Sócio não encontrado' });

    const commissionCount = await prisma.partnerCommission.count({ where: { partnerId: acc.id } });
    if (commissionCount > 0) {
      return res.status(400).json({
        error: 'Este sócio já tem comissões registradas. Desative em vez de remover, para preservar o histórico.',
      });
    }

    await prisma.partnerAccount.delete({ where: { id: acc.id } });
    res.json({ success: true });
  } catch (error) {
    console.error('[ADMIN/PARTNERS] Delete error:', error);
    res.status(500).json({ error: 'Erro ao remover sócio' });
  }
});

// ── Withdrawals queue ─────────────────────────────────────────────────────
// GET /api/admin/partner-withdrawals?status=pending|paid|rejected
router.get('/partner-withdrawals', async (req: AuthRequest, res: Response) => {
  try {
    const status = (req.query.status as string) || undefined;
    const rows = await prisma.partnerWithdrawal.findMany({
      where: status ? { status } : {},
      orderBy: { createdAt: 'desc' },
      include: {
        partner: {
          select: {
            displayName: true,
            user: { select: { id: true, name: true, email: true, phone: true } },
          },
        },
      },
      take: 200,
    });
    res.json({ withdrawals: rows });
  } catch (error) {
    console.error('[ADMIN/PARTNERS] withdrawals list error:', error);
    res.status(500).json({ error: 'Erro ao listar saques' });
  }
});

// POST /api/admin/partner-withdrawals/:id/approve — mark paid
router.post('/partner-withdrawals/:id/approve', superadminMiddleware, async (req: AuthRequest, res: Response) => {
  try {
    const wd = await prisma.partnerWithdrawal.findUnique({ where: { id: req.params.id } });
    if (!wd) return res.status(404).json({ error: 'Saque não encontrado' });
    if (wd.status !== 'pending') {
      return res.status(400).json({ error: `Saque já está ${wd.status}` });
    }
    const updated = await markWithdrawalPaid(wd.id, req.user!.id, req.body?.notes);
    // Auto-offboard: if this was a withdraw-only sócio cashing out their last
    // balance, deactivate + anonymize the account now (non-blocking).
    const off = await autoOffboardIfFullyPaid(wd.partnerId).catch(() => ({ anonymized: false }));
    res.json({ success: true, withdrawal: updated, offboarded: off.anonymized });
  } catch (error) {
    console.error('[ADMIN/PARTNERS] withdrawal approve error:', error);
    res.status(500).json({ error: 'Erro ao aprovar saque' });
  }
});

// POST /api/admin/partner-withdrawals/:id/reject — release balance back
router.post('/partner-withdrawals/:id/reject', superadminMiddleware, async (req: AuthRequest, res: Response) => {
  try {
    const wd = await prisma.partnerWithdrawal.findUnique({ where: { id: req.params.id } });
    if (!wd) return res.status(404).json({ error: 'Saque não encontrado' });
    if (wd.status !== 'pending') {
      return res.status(400).json({ error: `Saque já está ${wd.status}` });
    }
    const updated = await rejectWithdrawal(wd.id, req.user!.id, req.body?.notes);
    res.json({ success: true, withdrawal: updated });
  } catch (error) {
    console.error('[ADMIN/PARTNERS] withdrawal reject error:', error);
    res.status(500).json({ error: 'Erro ao rejeitar saque' });
  }
});

export default router;
