// Registry de ícones do menu da área de membros — Font Awesome 6 via
// react-icons/fa6, os MESMOS ícones da referência Kiwify (casa sólida,
// play em círculo sólido, marcas Instagram/Discord/WhatsApp, cartão de
// contato etc). A chave string é o que persiste em Course.config.menu[].icon.
// Usado pelo MembersShell (render) e pelo icon picker do editor.
import type { ComponentType } from "react";
import {
  FaHouse,
  FaCirclePlay,
  FaLink,
  FaInstagram,
  FaDiscord,
  FaWhatsapp,
  FaAddressCard,
  FaYoutube,
  FaTiktok,
  FaTelegram,
  FaXTwitter,
  FaFacebook,
  FaSpotify,
  FaBookOpen,
  FaCommentDots,
  FaUsers,
  FaEnvelope,
  FaPhone,
  FaGlobe,
  FaStar,
  FaHeart,
  FaGift,
  FaBolt,
  FaTrophy,
  FaGraduationCap,
  FaFileLines,
  FaDownload,
  FaCalendarDays,
  FaVideo,
  FaHeadphones,
  FaRocket,
  FaBullseye,
  FaWrench,
  FaBagShopping,
  FaMusic,
  FaGamepad,
} from "react-icons/fa6";

export type MemberIcon = ComponentType<{ size?: number | string; className?: string; style?: React.CSSProperties }>;

export const MEMBER_ICONS: Record<string, MemberIcon> = {
  house: FaHouse,
  play: FaCirclePlay,
  link: FaLink,
  instagram: FaInstagram,
  discord: FaDiscord,
  whatsapp: FaWhatsapp,
  "id-card": FaAddressCard,
  youtube: FaYoutube,
  tiktok: FaTiktok,
  telegram: FaTelegram,
  x: FaXTwitter,
  facebook: FaFacebook,
  spotify: FaSpotify,
  "book-open": FaBookOpen,
  "message-circle": FaCommentDots,
  users: FaUsers,
  mail: FaEnvelope,
  phone: FaPhone,
  globe: FaGlobe,
  star: FaStar,
  heart: FaHeart,
  gift: FaGift,
  zap: FaBolt,
  trophy: FaTrophy,
  "graduation-cap": FaGraduationCap,
  "file-text": FaFileLines,
  download: FaDownload,
  calendar: FaCalendarDays,
  video: FaVideo,
  headphones: FaHeadphones,
  rocket: FaRocket,
  target: FaBullseye,
  wrench: FaWrench,
  "shopping-bag": FaBagShopping,
  music: FaMusic,
  gamepad: FaGamepad,
};

export function memberIcon(name: string): MemberIcon {
  return MEMBER_ICONS[name] || FaLink;
}
