// Registry explícito de ícones do menu da área de membros (subset do lucide,
// importado nominalmente para o tree-shaking funcionar). Usado pelo
// MembersShell (render) e pelo icon picker do editor do admin — a chave
// string é o que persiste em Course.config.menu[].icon.
import type { LucideIcon } from "lucide-react";
import {
  House,
  Play,
  Link as LinkIcon,
  BookOpen,
  MessageCircle,
  Instagram,
  Youtube,
  Music,
  Users,
  Send,
  Globe,
  Star,
  Heart,
  Gift,
  Zap,
  Trophy,
  GraduationCap,
  FileText,
  Download,
  Calendar,
  Video,
  Headphones,
  Rocket,
  Target,
  Wrench,
  ShoppingBag,
  IdCard,
  Phone,
  Mail,
  Gamepad2,
} from "lucide-react";

export const MEMBER_ICONS: Record<string, LucideIcon> = {
  house: House,
  play: Play,
  link: LinkIcon,
  "book-open": BookOpen,
  "message-circle": MessageCircle,
  instagram: Instagram,
  youtube: Youtube,
  music: Music,
  users: Users,
  send: Send,
  globe: Globe,
  star: Star,
  heart: Heart,
  gift: Gift,
  zap: Zap,
  trophy: Trophy,
  "graduation-cap": GraduationCap,
  "file-text": FileText,
  download: Download,
  calendar: Calendar,
  video: Video,
  headphones: Headphones,
  rocket: Rocket,
  target: Target,
  wrench: Wrench,
  "shopping-bag": ShoppingBag,
  "id-card": IdCard,
  phone: Phone,
  mail: Mail,
  gamepad: Gamepad2,
};

export function memberIcon(name: string): LucideIcon {
  return MEMBER_ICONS[name] || LinkIcon;
}
